sudo: required

language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10

before_install:
  - pip install pytest
  - pip install coveralls
  - pip install pytest-cov
  - pip install pytest-mpl

install:
  - pip install -r requirements.txt

script:
  - python run_tests.py

after_success:
   - coveralls
